[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/aszo-div1"
  to = "/.netlify/functions/aszo-div1"
  status = 200

[[redirects]]
  from = "/api/aszo-div2"
  to = "/.netlify/functions/aszo-div2"
  status = 200

[[redirects]]
  from = "/api/asl-div1"
  to = "/.netlify/functions/asl-div1"
  status = 200

[[redirects]]
  from = "/api/asl-div2a"
  to = "/.netlify/functions/asl-div2a"
  status = 200

[[redirects]]
  from = "/api/asl-div2b"
  to = "/.netlify/functions/asl-div2b"
  status = 200

[[redirects]]
  from = "/api/asl-div1f"
  to = "/.netlify/functions/asl-div1f"
  status = 200
